const ADD_ALL = "ADD_ALL";
const SEARCH_DOG = "SEARCH_DOG";
const SLICE_DOGS = "SLICE_DOGS";
const ORDER_DOGS = "ORDER_DOGS";
const FILTER_DOGS = "FILTER_DOGS";
const UPDATE_TEMPERAMENTS = "UPDATE_TEMPERAMENTS";
//const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";



export {
  ADD_ALL,
  SEARCH_DOG,
  SLICE_DOGS,
  ORDER_DOGS,
  FILTER_DOGS,
  UPDATE_TEMPERAMENTS,
  //FILTER_BY_ORIGIN
};
